(autoload 'hexrgb-read-color                    "hexrgb" "" t)
(autoload 'hexrgb-complement                    "hexrgb" "" t)
(autoload 'hexrgb-hue                           "hexrgb" "" t)
(autoload 'hexrgb-saturation                    "hexrgb" "" t)
(autoload 'hexrgb-value                         "hexrgb" "" t)
(autoload 'hexrgb-red                           "hexrgb" "" t)
(autoload 'hexrgb-green                         "hexrgb" "" t)
(autoload 'hexrgb-blue                          "hexrgb" "" t)
(provide 'lib-hexrgb-epkg-install)
